const express = require("express")
const router = express.Router()
const user = require('./user')
const profile = require('./profile')
const menu = require('./menu')
const sample = require('./sample')
const order_chart =require('./order_chart')
const upload = require('./upload')
const download = require('./download')
const code = require('./code')
router.use(user)
router.use(menu)
router.use(sample)
router.use(order_chart)
router.use(upload)
router.use(download)
router.use(code)
router.use('/profiles',profile)
module.exports = router